### ISSUE TITLE
Simplify fork-and-pr.md?

### ISSUE THREAD

**Issue by arthurthefourth** [emerald-rubies/guides#3]
I haven't done much open source, so the fork and PR technique is pretty new to me, but I'm wondering if the process described in [fork-and-pr.md](https://github.com/emerald-rubies/guides/commit/733ef52a33a5d14d363bfcefc2771c6426a5785c) could be simplified a bit.

It doesn't look like the `upstream` branch is being used anywhere, so I'm wondering if it would be possible to remove Step 3 ("Add upstream remote"), modify Step 4 ("Create new feature branch") to fetch `origin` (which is automatically linked in Step 2) instead of `upstream`, and then build the feature branch off of `origin/master` or `master` instead?

**Comment by grepsedawk** [comment]
`upstream` is the "real" org's repo, so upstream/master is the "real and guaranteed up to date master". Usually _my_ origin/master becomes stale as I never update it.

**Comment by grepsedawk** [comment]
I'm open to suggestions to simplify, but the upstream piece is needed to fetch the official repo.
Closing this issue.
Thanks for asking!

**Comment by arthurthefourth** [comment]
Hmm, I still don't get this. If you're worried about `origin/master` being stale, shouldn't the instructions also include a merge with or rebase onto `upstream/master` after you make your commits? Otherwise, the commits are all built off of local `master`, which, if you've followed these steps exactly, is only a few minutes less stale than `origin/master`.

**Comment by grepsedawk** [comment]
In step 4, you check out upstream/master then branch off of that branch like so:
```
git checkout upstream/master
git checkout -b my-branch-name
```

**Comment by arthurthefourth** [comment]
Sure, but again, I'm talking about _after you make your commits_ now. At Step 4, upstream and origin are at most a few minutes different because you _just forked_ the repo in Step 2. The chances of origin going stale in that amount of time are pretty low. But then you write your code. Maybe it takes a few minutes, maybe it takes a few days. In the meantime, someone has already pushed their own code to upstream. The "upstream" your code is built on is no longer the tip of upstream/master; it's whatever commit was the tip of upstream/master when you fetched it in Step 4. Your code is now almost exactly as stale as it would have been if you had fetched origin/master and branched off of that. So if staleness is a concern, there should be a rebase/merge step at the end after the commits. If staleness isn't a concern, then it's much simpler to build the feature branch off of origin instead of upstream.

**Comment by grepsedawk** [comment]
Ah, I see what you're saying. I need to have something that states "repeat steps 4-7". That's why step 4 is the way it is, so you can continuously branch off the latest upstream/master.

**Comment by arthurthefourth** [comment]
Huh? There's no rebase or merge in steps 4-7; how would that solve the problem? This is starting to get confusing; let's chat through it on Slack when you get a chance - this afternoon or evening would be fine for me, as would any time after noon Eastern tomorrow.

**Comment by grepsedawk** [comment]
Going to vet this out offline.

**Comment by grepsedawk** [comment]
Going to fix up these guides and get my PR approved by @arthurthefourth
